parameters:
  variables: {}
  matrix: {}
  endpoint: ''

jobs:
- job: test
  timeoutInMinutes: 0
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')

  variables: ${{ parameters.default }}
  strategy:
    matrix: ${{ parameters.matrix }}

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: true
    persistCredentials: true

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      if ! rustup -V; then
        curl -sSf -o rustup-init.exe https://win.rustup.rs
        ./rustup-init.exe -y --default-toolchain none
        echo "##vso[task.setvariable variable=PATH;]${CARGO_HOME:-$USERPROFILE\.cargo}\bin;$PATH"
      fi
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: 'Install Rust (Windows)'

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      if ! rustup -V; then
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
        echo "##vso[task.setvariable variable=PATH;]${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
      fi
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: 'Install Rust (Darwin)'

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      if ! rustup -V; then
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
        echo "##vso[task.setvariable variable=PATH;]${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
      fi
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install -y gcc-multilib libssl-dev:i386 musl-tools
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: 'Install Rust (Linux)'

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      rustup toolchain install $RUST_LINT_TOOLCHAIN --no-self-update
      rustup component add rustfmt --toolchain $RUST_LINT_TOOLCHAIN
    displayName: Install Rust lint

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      cargo +$RUST_LINT_TOOLCHAIN fmt -- --check || (
        git reset --hard HEAD^2
        cargo +$RUST_LINT_TOOLCHAIN fmt
        git config user.email tidy.bot@example.com
        git config user.name "Tidy Bot"
        git add -A
        git commit -m "Automatic formatting with rustfmt"
        git -c http.extraheader="$(git config --get "http.$BUILD_REPOSITORY_URI.extraheader")" push --verbose "$SYSTEM_PULLREQUEST_SOURCEREPOSITORYURI" "HEAD:$SYSTEM_PULLREQUEST_SOURCEBRANCH"
        false
      )
    condition: eq(variables['Build.Reason'], 'PullRequest')
    displayName: Check & fix formatting

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      cargo +$RUST_LINT_TOOLCHAIN fmt -- --check
    condition: ne(variables['Build.Reason'], 'PullRequest')
    displayName: Check formatting

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      rustup component add clippy --toolchain $RUST_LINT_TOOLCHAIN
      for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do [ "$TARGET" = $(rustup target list --toolchain $RUST_LINT_TOOLCHAIN | grep default | grep -o -e '^[^ ]\+') ] || rustup target add --toolchain $RUST_LINT_TOOLCHAIN "$TARGET"; done
      for TOOLCHAIN in $RUST_TOOLCHAIN; do (
        if [ "$TOOLCHAIN" != "$RUST_LINT_TOOLCHAIN" ]; then
          rustup toolchain install $TOOLCHAIN --no-self-update
          for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do [ "$TARGET" = $(rustup target list --toolchain $TOOLCHAIN | grep default | grep -o -e '^[^ ]\+') ] || rustup target add --toolchain $TOOLCHAIN "$TARGET"; done
        fi
        rustc +$TOOLCHAIN -Vv
        cargo +$TOOLCHAIN -V
      ); done
    displayName: Install Rust matrix

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      export PKG_CONFIG_ALLOW_CROSS=1
      cargo +$RUST_LINT_TOOLCHAIN install cargo-print
      for TOOLCHAIN in $RUST_TOOLCHAIN; do (
        export TOOLCHAIN
        OLD_IFS=$IFS IFS=";" RUST_FLAGS="$RUST_FLAGS;"; for RUSTFLAGS in $RUST_FLAGS; do ( IFS=$OLD_IFS
          export RUSTFLAGS
          OLD_IFS=$IFS IFS=";" RUST_FEATURES="$RUST_FEATURES;"; for FEATURES in $RUST_FEATURES; do ( IFS=$OLD_IFS
            [ "$FEATURES" = "all" ] && FEATURES="" ALL_FEATURES="--all-features" || ALL_FEATURES=""
            export FEATURES
            export ALL_FEATURES
            PACKAGES=$(cargo +$RUST_LINT_TOOLCHAIN print publish)
            WORKSPACE_ROOT=$(pwd)
            for PACKAGE in $PACKAGES; do (
              PACKAGE_DIRECTORY=$(cargo +$RUST_LINT_TOOLCHAIN print directory "$PACKAGE")
              pushd "$PACKAGE_DIRECTORY" > /dev/null
              PACKAGE_CANONICALIZED=$(echo "${PACKAGE_DIRECTORY#$WORKSPACE_ROOT}" | tr '\' '/')
              [ -z "$PACKAGE_CANONICALIZED" ] || PACKAGE_CANONICALIZED+='/'
              FEATURES=$(echo "$FEATURES" | tr ' ' '\n' | sed -n -E "s|^${PACKAGE_CANONICALIZED}([^/]*)$|\1|p" | tr '\n' ' ')
              for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do (
                cargo +$RUST_LINT_TOOLCHAIN clippy --target "$TARGET" --all-targets --no-default-features --features "$FEATURES" $ALL_FEATURES -- -D warnings
              ); done
              for TARGET in $RUST_TARGET_BUILD; do (
                RUST_BACKTRACE=full cargo +$TOOLCHAIN test --no-run --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES
                case "${TARGET%%-*}" in i386|i686|x86_64) RUSTFLAGS="$RUSTFLAGS ";; esac
                RUST_BACKTRACE=full cargo +$TOOLCHAIN test --no-run --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES --release
              ); done
              for TARGET in $RUST_TARGET_RUN; do (
                RUST_BACKTRACE=full cargo +$TOOLCHAIN test --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES
                RUSTFLAGS="$RUSTFLAGS " RUST_BACKTRACE=full cargo +$TOOLCHAIN test --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES --release
                RUSTFLAGS="$RUSTFLAGS " RUST_BACKTRACE=full cargo +$TOOLCHAIN bench --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES
                examples=$(cargo +$RUST_LINT_TOOLCHAIN print examples --no-default-features --features "$FEATURES" $ALL_FEATURES)
                for example in $examples; do (
                  RUST_BACKTRACE=full cargo +$TOOLCHAIN run --target "$TARGET" --example "$example" --no-default-features --features "$FEATURES" $ALL_FEATURES
                  RUSTFLAGS="$RUSTFLAGS " RUST_BACKTRACE=full cargo +$TOOLCHAIN run --target "$TARGET" --example "$example" --no-default-features --features "$FEATURES" $ALL_FEATURES --release
                ); done
              ); done
              popd > /dev/null
            ); done
          ); done; IFS=$OLD_IFS
        ); done; IFS=$OLD_IFS
      ); done
    env:
      RUST_LINT_TOOLCHAIN: ${{ parameters.default.rust_lint_toolchain }}
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    displayName: Build & Run

  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      export PKG_CONFIG_ALLOW_CROSS=1
      FEATURES="${RUST_DOC_FEATURES-}"
      [ "$FEATURES" = "all" ] && FEATURES="" ALL_FEATURES="--all-features" || ALL_FEATURES=""
      for TARGET in $RUST_TARGET_CHECK $RUST_TARGET_BUILD $RUST_TARGET_RUN; do
        cargo +$RUST_LINT_TOOLCHAIN doc --no-deps --target "$TARGET" --no-default-features --features "$FEATURES" $ALL_FEATURES &>/dev/null
      done
      #cargo +$RUST_LINT_TOOLCHAIN package
    displayName: Check documentation


- job: publish
  pool:
    vmImage: 'ubuntu-16.04'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  steps:
  - bash: |
      set -o errexit; set -o pipefail; set -o nounset; set -o xtrace; shopt -s nullglob;
      if ! rustup -V; then
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
        echo "##vso[task.setvariable variable=PATH;]${CARGO_HOME:-$HOME/.cargo}/bin:$PATH"
      fi
      rustup toolchain install $RUST_LINT_TOOLCHAIN --no-self-update
      cargo +$RUST_LINT_TOOLCHAIN install cargo-print
      cargo +$RUST_LINT_TOOLCHAIN generate-lockfile
      PACKAGES=$(cargo +$RUST_LINT_TOOLCHAIN print publish)
      TOP_PACKAGE=$(cargo +$RUST_LINT_TOOLCHAIN print package)
      for PACKAGE in $PACKAGES; do (
        PACKAGE_DIRECTORY=$(cargo +$RUST_LINT_TOOLCHAIN print directory "$PACKAGE")
        pushd "$PACKAGE_DIRECTORY" > /dev/null
        [ "$TOP_PACKAGE" = "$PACKAGE" ] || (cargo +$RUST_LINT_TOOLCHAIN publish && sleep 120) ||:
        popd > /dev/null
      ); done
      if cargo +$RUST_LINT_TOOLCHAIN publish; then
        CARGO_PKGID=$(cargo +$RUST_LINT_TOOLCHAIN pkgid | cut -d# -f2 | cut -d: -f2)
        echo "##vso[task.setvariable variable=release_tag]v$CARGO_PKGID"
        echo "##vso[task.setvariable variable=release_date]$(date +%Y-%m-%d)"
      fi
    env:
      RUST_LINT_TOOLCHAIN: ${{ parameters.default.rust_lint_toolchain }}
      CARGO_REGISTRY_TOKEN: $(cargo_registry_token)
    displayName: Cargo publish

  - task: GithubRelease@0
    inputs:
      gitHubConnection: ${{ parameters.endpoint }}
      tagSource: 'manual'
      tag: '$(release_tag)'
      title: '$(release_tag) - $(release_date)'
      addChangeLog: true
      compareWith: lastRelease
    condition: variables.release_tag
